title: Blog personal
description: vida personal relacionada con la carrera de software 
author: Anderson Jordan
avatar: https://avatars2.githubusercontent.com/u/69701126?s=460&u=37593b61392a7032fc66322e964776b9d198ee11&v=4
email: andjor2019@GMAIL.COM

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - LEER
  - jekyll-theme-hamilton.gemspec


    -
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
